### PR TITLE
Metamask Derive Flow - prompt for messaging key randomness up front

### PR DESCRIPTION
**Pull request by lazynina**

### CODE REVIEW

**Comment by sungkhum** [comment]
@lazynina I think this is causing a new error for users using Identity to login and approve a derived key. It doesn't work anymore and getting this error 

Error getting messaging key randomness
Error: encrypted user not found

main.24466aabf5218981.js:1 Error: encrypted user not found
    at n.requiresMessagingKeyRandomness (main.24466aabf5218981.js:1:2829459)
    at n.<anonymous> (main.24466aabf5218981.js:1:2828882)
    at Generator.next (<anonymous>)
    at main.24466aabf5218981.js:1:3097522
    at new w (polyfills.7e74a088637eda8e.js:1:53474)
    at U (main.24466aabf5218981.js:1:3097257)
    at n.approveDerivedKey (main.24466aabf5218981.js:1:2828832)
    at main.24466aabf5218981.js:1:2826013
    at Jv (main.24466aabf5218981.js:1:2211506)
    at M (main.24466aabf5218981.js:1:2211668)

Using this for the identity window: 
```
https://identity.deso.org/derive?expirationDays=1&transactionSpendingLimitResponse=%7B%22GlobalDESOLimit%22:1000200000,%22TransactionCountLimitMap%22:%7B%22AUTHORIZE_DERIVED_KEY%22:2,%22BASIC_TRANSFER%22:2%7D,%22NFTOperationLimitMap%22:%7B%22%22:%7B%220%22:%7B%22nft_bid%22:1%7D%7D%7D%7D
```

**Comment by lazynina** [comment]
> @lazynina I think this is causing a new error for users using Identity to login and approve a derived key. It doesn't work anymore and getting this error
> 
> Error getting messaging key randomness Error: encrypted user not found
> 
> main.24466aabf5218981.js:1 Error: encrypted user not found at n.requiresMessagingKeyRandomness (main.24466aabf5218981.js:1:2829459) at n. (main.24466aabf5218981.js:1:2828882) at Generator.next () at main.24466aabf5218981.js:1:3097522 at new w (polyfills.7e74a088637eda8e.js:1:53474) at U (main.24466aabf5218981.js:1:3097257) at n.approveDerivedKey (main.24466aabf5218981.js:1:2828832) at main.24466aabf5218981.js:1:2826013 at Jv (main.24466aabf5218981.js:1:2211506) at M (main.24466aabf5218981.js:1:2211668)
> 
> Using this for the identity window:
> 
> ```
> https://identity.deso.org/derive?expirationDays=1&transactionSpendingLimitResponse=%7B%22GlobalDESOLimit%22:1000200000,%22TransactionCountLimitMap%22:%7B%22AUTHORIZE_DERIVED_KEY%22:2,%22BASIC_TRANSFER%22:2%7D,%22NFTOperationLimitMap%22:%7B%22%22:%7B%220%22:%7B%22nft_bid%22:1%7D%7D%7D%7D
> ```

@sungkhum - do you have a sample app that I can test in? This error should only pop up if the user doesn't exist in identity's local storage on the device

**Comment by sungkhum** [comment]
@lazynina Yeah, you can try to login here https://mint.tipsyelfnft.com/

It won't spend the money unless you click the mint button, but right now you can't derive a key.

**Comment by lazynina** [comment]
@sungkhum - working on a fix, should be resolved shortly

**Comment by sungkhum** [comment]
Thanks @lazynina !

**Comment by lazynina** [comment]
@sungkhum - appears to be resolved with #214 which is live now

**Comment by sungkhum** [comment]
Thank you - it's fixed @lazynina

**Pull request merged**
